### ISSUE TITLE
Any plans to upgrade the code to Swift 3?

### ISSUE THREAD

**Issue by starlight173** [milanpanchal/Swifty-Extensions#1]
The default migration tool to Swift 3.0 in Xcode 8 leaves a few errors , most notably the use of init function & comparable protocol. It'd be nice to have an updated this useful extension source available for Swift 3.0.

**Comment by milanpanchal** [comment]
Yes in a week will update to Swift 3.0

**Comment by milanpanchal** [comment]
Update to Swift 5
